import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReactQueryProvider } from "@/providers/ReactQueryProvider";
import { MuiLocalizationProvider } from "@/providers/MuiLocalizationProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <AppRouterCacheProvider>
                    <ReactQueryProvider>
                        <MuiLocalizationProvider>
                            <main className="my-8 mx-12">{children}</main>
                        </MuiLocalizationProvider>
                    </ReactQueryProvider>
                </AppRouterCacheProvider>
            </body>
        </html>
    );
}
